language: python

python:
 - pypy
 - pypy3
 - 2.7
 - 3.4
 - 3.5
 - 3.6

sudo: false

install:
 - pip install pycodestyle pyflakes

script:
 # Tests
 - python test_bbcrealtime.py

 # Static analysis
 - pyflakes .
 - pycodestyle --statistics --count .

matrix:
  fast_finish: true
