language: python
cache: pip

matrix:
  fast_finish: true
  include:
    - python: 3.7
      dist: xenial
    - python: 3.6

install:
 - pip install --upgrade pip
 - pip install --upgrade black flake8
 - pip install --upgrade -r requirements.txt

script:
 # Tests
 - python test_bbcrealtime.py

 # Static analysis
 - flake8
 - black --check --diff .
